### PR TITLE
Ready: Add new blog post about geth tooling

### PR DESCRIPTION
**Pull request by adrianbrink**
@nylira How do we include pictures in our blog posts?

### CODE REVIEW

**Comment by nylira** [comment]
@adrianbrink, I updated the docs for the site with an example for including images:

https://github.com/tendermint/tendermint.github.io/blob/develop/CONTRIBUTING.md

**Comment by nylira** [comment]
Is this ready to be published Adrian?

**Comment by adrianbrink** [comment]
@nylira This blog post is good to go now, but I can't build it locally after adding the image docs according to your [explanation](https://github.com/tendermint/tendermint.github.io/blob/develop/CONTRIBUTING.md#include-images). Could you check why?

I am getting this error:
```
➜  tendermint.github.io git:(feature/adrian-ethermint) ✗ yarn run blog
yarn run v0.24.5
$ node build/blog.js
/Users/adrian/projects/tendermint/tendermint.github.io/node_modules/to-no-case/index.js:28
  return string.toLowerCase()
               ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at toNoCase (/Users/adrian/projects/tendermint/tendermint.github.io/node_modules/to-no-case/index.js:28:16)
    at toSpaceCase (/Users/adrian/projects/tendermint/tendermint.github.io/node_modules/to-space-case/index.js:18:10)
    at toSlugCase (/Users/adrian/projects/tendermint/tendermint.github.io/node_modules/to-slug-case/index.js:18:10)
    at markdownToObject (/Users/adrian/projects/tendermint/tendermint.github.io/build/blog.js:41:17)
    at Object.<anonymous> (/Users/adrian/projects/tendermint/tendermint.github.io/build/blog.js:68:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I ran `yarn install` and `yarn run blog` and I was in the top-level folder.

**Comment by nylira** [comment]
Looks like there was just an extra double quote mark.

**Pull request merged**
