### PR TITLE
Pull docs from tendermint/tendermint

### PR DESCRIPTION
**Pull request by keppel**
`npm run docs` will now put github.com/tendermint/tendermint/docs/ -> into content/docs/

This PR probably shouldn't be merged until the [docs make it to master on tendermint/tendermint](https://github.com/tendermint/tendermint/pull/538), but I tested this by changing the url in `docs-retrieve.js` to `https://github.com/zramsay/tendermint/archive/docs-rework.zip`.

### CODE REVIEW

**Comment by zramsay** [comment]
tendermint recently released with the docs changes ... let's get this merged in & added to the CI build for site. @keppel can you fix the conflict?

**Comment by nylira** [comment]
@keppel Please help fix these issues with documentation import. This is what I can see after bringing in the changes to develop to test:

screen shot 2017-08-15 at 13 10 53

The **Intro** page has an `Index` item in the sidebar that 404s because it links to `/intro/index` instead of `/intro`. Also, number 4 on the Intro page has disappeared: `<router-link :to="'/download'" exact>4. Getting Started</router-link>` should appear after `3. Consensus Overview`.

screen shot 2017-08-15 at 13 10 55

The **Documentation** page is now missing the entire `Getting Started` section, as well as a link to the `Download Tendermint` page.

Please compare these screenshots to the live website: https://tendermint.com/docs

**Comment by keppel** [comment]
I resolved the conflicts, @nylira how's that look?

**Comment by zramsay** [comment]
we will be moving all our docs to Sphinx/read the docs combo like in ethermint. This will simplify things but makes this PR obsolete.

**Pull request closed without merging**
